/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2018-07-10 13:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.net.anotheria.moskito.webui.tracers.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Tracers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/moskito-webui-2.8.7.jar", Long.valueOf(1527002124000L));
    _jspx_dependants.put("/WEB-INF/lib/ano-tags-2.1.1.jar", Long.valueOf(1475585378000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1421557168000L));
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/ano-tags-2.1.1.jar!/META-INF/ano-tags.tld", Long.valueOf(1475585374000L));
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/moskito-webui-2.8.7.jar!/META-INF/moskito-tags.tld", Long.valueOf(1527002120000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Header.jsp", out, false);
      out.write("\n");
      out.write("<section id=\"main\">\n");
      out.write("    <div class=\"content\">\n");
      out.write("\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <div class=\"box-title\">\n");
      out.write("                <a class=\"accordion-toggle tooltip-bottom\" title=\"Close/Open\" data-toggle=\"collapse\" href=\"#collapse1\"><i class=\"fa fa-caret-down\"></i></a>\n");
      out.write("                <h3 class=\"pull-left\">\n");
      out.write("                    MoSKito Tracers.\n");
      out.write("                </h3>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"collapse1\" class=\"box-content accordion-body collapse in\">\n");
      out.write("                <div class=\"paddner\">\n");
      out.write("                    MoSKito Tracers are monitoring points that will log the usage of a certain producer whenever a call runs through them. Not all MoSKito producer support tracing. You can configure a new tracer either from producer detail view or via config.\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <div class=\"box-title\">\n");
      out.write("                <a class=\"accordion-toggle tooltip-bottom\" title=\"Close/Open\" data-toggle=\"collapse\" href=\"#collapse2\"><i class=\"fa fa-caret-down\"></i></a>\n");
      out.write("                <h3 class=\"pull-left\">\n");
      out.write("                    Tracers (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracersCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\n");
      out.write("                </h3>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"collapse2\" class=\"box-content accordion-body collapse in\">\n");
      out.write("                <table class=\"table table-striped\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Name / ProducerId</th>\n");
      out.write("                        <th>Enabled</th>\n");
      out.write("                        <th>Current entries</th>\n");
      out.write("                        <th>Total calls seen</th>\n");
      out.write("                        <th class=\"th-actions\"></th>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    ");
      //  ano:iterate
      net.anotheria.tags.IterateTag _jspx_th_ano_005fiterate_005f0 = (net.anotheria.tags.IterateTag) _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.get(net.anotheria.tags.IterateTag.class);
      boolean _jspx_th_ano_005fiterate_005f0_reused = false;
      try {
        _jspx_th_ano_005fiterate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_ano_005fiterate_005f0.setParent(null);
        // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(44,20) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ano_005fiterate_005f0.setName("tracers");
        // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(44,20) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ano_005fiterate_005f0.setType("net.anotheria.moskito.webui.tracers.api.TracerAO");
        // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(44,20) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ano_005fiterate_005f0.setId("tracer");
        // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(44,20) name = indexId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ano_005fiterate_005f0.setIndexId("index");
        int _jspx_eval_ano_005fiterate_005f0 = _jspx_th_ano_005fiterate_005f0.doStartTag();
        if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          net.anotheria.moskito.webui.tracers.api.TracerAO tracer = null;
          java.lang.Integer index = null;
          if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ano_005fiterate_005f0);
          }
          tracer = (net.anotheria.moskito.webui.tracers.api.TracerAO) _jspx_page_context.findAttribute("tracer");
          index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
          do {
            out.write("\n");
            out.write("                        <tr>\n");
            out.write("                            <td>");
            if (_jspx_meth_mos_005fdeepLink_005f0(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("</td>\n");
            out.write("                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.enabled}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.entryCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.totalEntryCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                            <td>\n");
            out.write("                                ");
            if (_jspx_meth_mos_005fdeepLink_005f1(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_mos_005fdeepLink_005f4(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                                ");
            if (_jspx_meth_mos_005fdeepLink_005f5(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                            </td>\n");
            out.write("                        </tr>\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_ano_005fiterate_005f0.doAfterBody();
            tracer = (net.anotheria.moskito.webui.tracers.api.TracerAO) _jspx_page_context.findAttribute("tracer");
            index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_ano_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.reuse(_jspx_th_ano_005fiterate_005f0);
        _jspx_th_ano_005fiterate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fiterate_005f0_reused);
      }
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f0 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f0);
    try {
      _jspx_th_mos_005fdeepLink_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f0.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(46,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f0.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskTracer?pProducerId=${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f0, null));
      _jspx_th_mos_005fdeepLink_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f1 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f1);
    try {
      _jspx_th_mos_005fdeepLink_005f1.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f1.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(51,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f1.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskRemoveTracer?pProducerId=${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(51,32) null
      _jspx_th_mos_005fdeepLink_005f1.setDynamicAttribute(null, "class", "action-icon delete-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(51,32) null
      _jspx_th_mos_005fdeepLink_005f1.setDynamicAttribute(null, "title", "Delete");
      _jspx_th_mos_005fdeepLink_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f1, null));
      _jspx_th_mos_005fdeepLink_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(52,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.enabled}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    ");
          if (_jspx_meth_mos_005fdeepLink_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f2 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f2);
    try {
      _jspx_th_mos_005fdeepLink_005f2.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f2.setParent(_jspx_th_c_005fif_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(53,36) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f2.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskDisableTracer?pProducerId=${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(53,36) null
      _jspx_th_mos_005fdeepLink_005f2.setDynamicAttribute(null, "class", "action-icon toggle-on-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(53,36) null
      _jspx_th_mos_005fdeepLink_005f2.setDynamicAttribute(null, "title", "On - Disable");
      _jspx_th_mos_005fdeepLink_005f2.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f2, null));
      _jspx_th_mos_005fdeepLink_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(55,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.disabled}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                    ");
          if (_jspx_meth_mos_005fdeepLink_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f3 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f3);
    try {
      _jspx_th_mos_005fdeepLink_005f3.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f3.setParent(_jspx_th_c_005fif_005f1);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(56,36) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f3.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskEnableTracer?pProducerId=${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(56,36) null
      _jspx_th_mos_005fdeepLink_005f3.setDynamicAttribute(null, "class", "action-icon toggle-off-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(56,36) null
      _jspx_th_mos_005fdeepLink_005f3.setDynamicAttribute(null, "title", "Off - Enable");
      _jspx_th_mos_005fdeepLink_005f3.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f3, null));
      _jspx_th_mos_005fdeepLink_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f4 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f4);
    try {
      _jspx_th_mos_005fdeepLink_005f4.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f4.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(58,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f4.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskShowProducer?pProducerId=${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(58,32) null
      _jspx_th_mos_005fdeepLink_005f4.setDynamicAttribute(null, "class", "action-icon show-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(58,32) null
      _jspx_th_mos_005fdeepLink_005f4.setDynamicAttribute(null, "title", "ShowProducer");
      _jspx_th_mos_005fdeepLink_005f4.setJspBody(new Helper( 4, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f4, null));
      _jspx_th_mos_005fdeepLink_005f4.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f5 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f5);
    try {
      _jspx_th_mos_005fdeepLink_005f5.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f5.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(59,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f5.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskAnalyzeJourney?pJourneyName=Traced-${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(59,32) null
      _jspx_th_mos_005fdeepLink_005f5.setDynamicAttribute(null, "class", "action-icon show-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(59,32) null
      _jspx_th_mos_005fdeepLink_005f5.setDynamicAttribute(null, "title", "");
      // /net/anotheria/moskito/webui/tracers/jsp/Tracers.jsp(59,32) null
      _jspx_th_mos_005fdeepLink_005f5.setDynamicAttribute(null, "data-original-title", (java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Analyze all traced calls in ${tracer.producerId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f5.setJspBody(new Helper( 5, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f5, null));
      _jspx_th_mos_005fdeepLink_005f5.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f5);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tracer.producerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-ban\"></i>");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-toggle-on\"></i>");
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-toggle-off\"></i>");
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-search-plus\"></i>");
      return false;
    }
    public boolean invoke5( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-search-plus\"></i>");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
          case 5:
            invoke5( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
