/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2018-07-10 14:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.net.anotheria.moskito.webui.journey.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Journeys_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/moskito-webui-2.8.7.jar", Long.valueOf(1527002124000L));
    _jspx_dependants.put("/WEB-INF/lib/ano-tags-2.1.1.jar", Long.valueOf(1475585378000L));
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/ano-tags-2.1.1.jar!/META-INF/ano-tags.tld", Long.valueOf(1475585374000L));
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/moskito-webui-2.8.7.jar!/META-INF/moskito-tags.tld", Long.valueOf(1527002120000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fnotPresent_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fpresent_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fequal_0026_005fvalue_005fproperty_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fano_005fnotPresent_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fano_005fpresent_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fano_005fequal_0026_005fvalue_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fano_005fnotPresent_0026_005fname.release();
    _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fano_005fpresent_0026_005fname.release();
    _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.release();
    _005fjspx_005ftagPool_005fano_005fequal_0026_005fvalue_005fproperty_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Header.jsp", out, false);
      out.write("\n");
      out.write("<section id=\"main\">\n");
      out.write("    ");
      if (_jspx_meth_ano_005fnotPresent_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"content\">\n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function new_journey(name){\n");
      out.write("                var link = \"");
      if (_jspx_meth_ano_005fwrite_005f0(_jspx_page_context))
        return;
      out.write("\"+name;\n");
      out.write("                window.open(link );\n");
      out.write("                //force reload\n");
      out.write("                location.href = location.href;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function stop_journey(name){\n");
      out.write("                var link = \"");
      if (_jspx_meth_ano_005fwrite_005f1(_jspx_page_context))
        return;
      out.write("\"+name;\n");
      out.write("                window.open(link);\n");
      out.write("                //force reload\n");
      out.write("                location.href = location.href;\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <div class=\"box-title\">\n");
      out.write("                <h3 class=\"pull-left\">\n");
      out.write("                    Journeys\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"box-right-nav\">\n");
      out.write("                    <a href=\"\" class=\"tooltip-bottom\" title=\"Help\"><i class=\"fa fa-info-circle\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"box-content\">\n");
      out.write("                <div class=\"paddner\">\n");
      out.write("                    <div class=\"jour-left form-inline\">\n");
      out.write("                        <p>To start a new journey now enter the name for the journey</p>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <form name=\"NEWJOURNEY\">\n");
      out.write("                            <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Enter Name\">\n");
      out.write("                            <button class=\"btn btn-success\" onclick=\"new_journey(document.NEWJOURNEY.name.value); return false\">Start</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"jour-right\">\n");
      out.write("                        <p>To record a new journey add <span class=\"text-green\">mskJourney=start&mskJourneyName=JOURNEY_NAME</span> to any url on this server.</p>\n");
      out.write("                        <p>To stop journey recording add <span class=\"text-green\">mskJourney=stop&mskJourneyName=JOURNEY_NAME</span> to any url on this server.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      //  ano:present
      net.anotheria.tags.PresentTag _jspx_th_ano_005fpresent_005f0 = (net.anotheria.tags.PresentTag) _005fjspx_005ftagPool_005fano_005fpresent_0026_005fname.get(net.anotheria.tags.PresentTag.class);
      boolean _jspx_th_ano_005fpresent_005f0_reused = false;
      try {
        _jspx_th_ano_005fpresent_005f0.setPageContext(_jspx_page_context);
        _jspx_th_ano_005fpresent_005f0.setParent(null);
        // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(63,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ano_005fpresent_005f0.setName("journeysPresent");
        int _jspx_eval_ano_005fpresent_005f0 = _jspx_th_ano_005fpresent_005f0.doStartTag();
        if (_jspx_eval_ano_005fpresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("        <div class=\"box\">\n");
            out.write("            <div class=\"box-title\">\n");
            out.write("                <h3 class=\"pull-left\">\n");
            out.write("                    Recorded journeys.\n");
            out.write("                </h3>\n");
            out.write("                <div class=\"box-right-nav\">\n");
            out.write("                    <a href=\"\" class=\"tooltip-bottom\" title=\"Help\"><i class=\"fa fa-info-circle\"></i></a>\n");
            out.write("                </div>\n");
            out.write("            </div>\n");
            out.write("            <div class=\"box-content\">\n");
            out.write("                <table class=\"table table-striped tablesorter\">\n");
            out.write("                    <thead>\n");
            out.write("                    <tr>\n");
            out.write("                        <th>Journey <i class=\"fa fa-caret-down\"></i></th>\n");
            out.write("                        <th>Started <i class=\"fa fa-caret-down\"></i></th>\n");
            out.write("                        <th>Last activity <i class=\"fa fa-caret-down\"></i></th>\n");
            out.write("                        <th>Calls <i class=\"fa fa-caret-down\"></i></th>\n");
            out.write("                        <th>Active <i class=\"fa fa-caret-down\"></i></th>\n");
            out.write("                        <th class=\"th-actions\">&nbsp;</th>\n");
            out.write("                    </tr>\n");
            out.write("                    </thead>\n");
            out.write("                    <tbody>\n");
            out.write("                    ");
            //  ano:iterate
            net.anotheria.tags.IterateTag _jspx_th_ano_005fiterate_005f0 = (net.anotheria.tags.IterateTag) _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.get(net.anotheria.tags.IterateTag.class);
            boolean _jspx_th_ano_005fiterate_005f0_reused = false;
            try {
              _jspx_th_ano_005fiterate_005f0.setPageContext(_jspx_page_context);
              _jspx_th_ano_005fiterate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ano_005fpresent_005f0);
              // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(86,20) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ano_005fiterate_005f0.setName("journeys");
              // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(86,20) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ano_005fiterate_005f0.setType("net.anotheria.moskito.webui.journey.api.JourneyListItemAO");
              // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(86,20) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ano_005fiterate_005f0.setId("journey");
              // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(86,20) name = indexId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ano_005fiterate_005f0.setIndexId("index");
              int _jspx_eval_ano_005fiterate_005f0 = _jspx_th_ano_005fiterate_005f0.doStartTag();
              if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                net.anotheria.moskito.webui.journey.api.JourneyListItemAO journey = null;
                java.lang.Integer index = null;
                if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_ano_005fiterate_005f0);
                }
                journey = (net.anotheria.moskito.webui.journey.api.JourneyListItemAO) _jspx_page_context.findAttribute("journey");
                index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
                do {
                  out.write("\n");
                  out.write("                        <tr>\n");
                  out.write("                            <td>");
                  if (_jspx_meth_mos_005fdeepLink_005f0(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
                    return;
                  out.write("</td>\n");
                  out.write("                            <td>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.created}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</td>\n");
                  out.write("                            <td>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.lastActivity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</td>\n");
                  out.write("                            <td>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.numberOfCalls}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</td>\n");
                  out.write("                            <td>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.active}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("&nbsp;\n");
                  out.write("                                ");
                  if (_jspx_meth_ano_005fequal_005f0(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                            </td>\n");
                  out.write("\n");
                  out.write("                            <td>\n");
                  out.write("                                ");
                  if (_jspx_meth_mos_005fdeepLink_005f1(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                                ");
                  if (_jspx_meth_mos_005fdeepLink_005f2(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                                ");
                  if (_jspx_meth_mos_005fdeepLink_005f3(_jspx_th_ano_005fiterate_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("\n");
                  out.write("                            </td>\n");
                  out.write("\n");
                  out.write("                        </tr>\n");
                  out.write("                    ");
                  int evalDoAfterBody = _jspx_th_ano_005fiterate_005f0.doAfterBody();
                  journey = (net.anotheria.moskito.webui.journey.api.JourneyListItemAO) _jspx_page_context.findAttribute("journey");
                  index = (java.lang.Integer) _jspx_page_context.findAttribute("index");
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_ano_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_ano_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fano_005fiterate_0026_005ftype_005fname_005findexId_005fid.reuse(_jspx_th_ano_005fiterate_005f0);
              _jspx_th_ano_005fiterate_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fiterate_005f0_reused);
            }
            out.write("\n");
            out.write("                    </tbody>\n");
            out.write("                </table>\n");
            out.write("            </div>\n");
            out.write("        </div>\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_ano_005fpresent_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_ano_005fpresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fano_005fpresent_0026_005fname.reuse(_jspx_th_ano_005fpresent_005f0);
        _jspx_th_ano_005fpresent_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fpresent_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fpresent_005f0_reused);
      }
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Footer.jsp", out, false);
      out.write("\n");
      out.write("</section>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ano_005fnotPresent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:notPresent
    net.anotheria.tags.NotPresentTag _jspx_th_ano_005fnotPresent_005f0 = (net.anotheria.tags.NotPresentTag) _005fjspx_005ftagPool_005fano_005fnotPresent_0026_005fname.get(net.anotheria.tags.NotPresentTag.class);
    boolean _jspx_th_ano_005fnotPresent_005f0_reused = false;
    try {
      _jspx_th_ano_005fnotPresent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fnotPresent_005f0.setParent(null);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(9,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fnotPresent_005f0.setName("journeysPresent");
      int _jspx_eval_ano_005fnotPresent_005f0 = _jspx_th_ano_005fnotPresent_005f0.doStartTag();
      if (_jspx_eval_ano_005fnotPresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"alert alert-success alert-dismissable\">\n");
          out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\n");
          out.write("            You have no journeys yet, you can start a journey by following the instructions below or programmatically.\n");
          out.write("        </div>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_ano_005fnotPresent_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ano_005fnotPresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fnotPresent_0026_005fname.reuse(_jspx_th_ano_005fnotPresent_005f0);
      _jspx_th_ano_005fnotPresent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fnotPresent_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fnotPresent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f0 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f0_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f0.setParent(null);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(21,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f0.setName("new_journey_url");
      int _jspx_eval_ano_005fwrite_005f0 = _jspx_th_ano_005fwrite_005f0.doStartTag();
      if (_jspx_th_ano_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f0);
      _jspx_th_ano_005fwrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f1 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f1_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f1.setParent(null);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(28,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f1.setName("stop_journey_url");
      int _jspx_eval_ano_005fwrite_005f1 = _jspx_th_ano_005fwrite_005f1.doStartTag();
      if (_jspx_th_ano_005fwrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f1);
      _jspx_th_ano_005fwrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f1, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f0 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f0);
    try {
      _jspx_th_mos_005fdeepLink_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f0.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(88,32) null
      _jspx_th_mos_005fdeepLink_005f0.setDynamicAttribute(null, "class", "tooltip-bottom");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(88,32) null
      _jspx_th_mos_005fdeepLink_005f0.setDynamicAttribute(null, "title", (java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Show steps in journey ${journey.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(88,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f0.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskShowJourney?pJourneyName=${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f0, null));
      _jspx_th_mos_005fdeepLink_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fequal_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:equal
    net.anotheria.tags.EqualTag _jspx_th_ano_005fequal_005f0 = (net.anotheria.tags.EqualTag) _005fjspx_005ftagPool_005fano_005fequal_0026_005fvalue_005fproperty_005fname.get(net.anotheria.tags.EqualTag.class);
    boolean _jspx_th_ano_005fequal_005f0_reused = false;
    try {
      _jspx_th_ano_005fequal_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fequal_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(93,32) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fequal_005f0.setName("journey");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(93,32) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fequal_005f0.setProperty("active");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(93,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fequal_005f0.setValue("true");
      int _jspx_eval_ano_005fequal_005f0 = _jspx_th_ano_005fequal_005f0.doStartTag();
      if (_jspx_eval_ano_005fequal_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("&nbsp;(<a href=\"#\" onclick=\"stop_journey('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">stop</a>)");
          int evalDoAfterBody = _jspx_th_ano_005fequal_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_ano_005fequal_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fequal_0026_005fvalue_005fproperty_005fname.reuse(_jspx_th_ano_005fequal_005f0);
      _jspx_th_ano_005fequal_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fequal_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fequal_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f1 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f1);
    try {
      _jspx_th_mos_005fdeepLink_005f1.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f1.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(97,32) null
      _jspx_th_mos_005fdeepLink_005f1.setDynamicAttribute(null, "class", "action-icon delete-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(97,32) null
      _jspx_th_mos_005fdeepLink_005f1.setDynamicAttribute(null, "title", "");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(97,32) null
      _jspx_th_mos_005fdeepLink_005f1.setDynamicAttribute(null, "data-original-title", (java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Delete ${journey.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(97,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f1.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskDeleteJourney?pJourneyName=${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f1, null));
      _jspx_th_mos_005fdeepLink_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f2 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f2);
    try {
      _jspx_th_mos_005fdeepLink_005f2.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f2.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(98,32) null
      _jspx_th_mos_005fdeepLink_005f2.setDynamicAttribute(null, "class", "action-icon show-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(98,32) null
      _jspx_th_mos_005fdeepLink_005f2.setDynamicAttribute(null, "title", "");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(98,32) null
      _jspx_th_mos_005fdeepLink_005f2.setDynamicAttribute(null, "data-original-title", (java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Show steps in journey ${journey.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(98,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f2.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskShowJourney?pJourneyName=${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f2.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f2, null));
      _jspx_th_mos_005fdeepLink_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_mos_005fdeepLink_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_ano_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mos:deepLink
    net.anotheria.moskito.webui.shared.tags.DeepLinkTag _jspx_th_mos_005fdeepLink_005f3 = new net.anotheria.moskito.webui.shared.tags.DeepLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mos_005fdeepLink_005f3);
    try {
      _jspx_th_mos_005fdeepLink_005f3.setJspContext(_jspx_page_context);
      _jspx_th_mos_005fdeepLink_005f3.setParent(_jspx_th_ano_005fiterate_005f0);
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(99,32) null
      _jspx_th_mos_005fdeepLink_005f3.setDynamicAttribute(null, "class", "action-icon show-icon tooltip-bottom");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(99,32) null
      _jspx_th_mos_005fdeepLink_005f3.setDynamicAttribute(null, "title", "");
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(99,32) null
      _jspx_th_mos_005fdeepLink_005f3.setDynamicAttribute(null, "data-original-title", (java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Analyze journey ${journey.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /net/anotheria/moskito/webui/journey/jsp/Journeys.jsp(99,32) name = href type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mos_005fdeepLink_005f3.setHref((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("mskAnalyzeJourney?pJourneyName=${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mos_005fdeepLink_005f3.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_mos_005fdeepLink_005f3, null));
      _jspx_th_mos_005fdeepLink_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mos_005fdeepLink_005f3);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-ban\"></i>");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-search\"></i>");
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<i class=\"fa fa-search-plus\"></i>");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
