/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2018-07-10 13:38:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.net.anotheria.moskito.webui.threads.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Threads_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/ano-tags-2.1.1.jar", Long.valueOf(1475585378000L));
    _jspx_dependants.put("jar:file:/home/matheus/JCL-APP/app/src/lib/moskito/moskito-inspect/tomcat/webapps/moskito/WEB-INF/lib/ano-tags-2.1.1.jar!/META-INF/ano-tags.tld", Long.valueOf(1475585374000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"main\">\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <div class=\"box-title\">\n");
      out.write("                <a class=\"accordion-toggle tooltip-bottom\" title=\"Close/Open\" data-toggle=\"collapse\" href=\"#collapse1\"><i class=\"fa fa-caret-down\"></i></a>\n");
      out.write("                <h3 class=\"pull-left\">\n");
      out.write("                    Threads stats\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"box-right-nav\">\n");
      out.write("                    <a href=\"\" class=\"tooltip-bottom\" title=\"Help\"><i class=\"fa fa-info-circle\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"collapse1\" class=\"box-content accordion-body collapse in\">\n");
      out.write("                <table class=\"table table-striped tablesorter\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Stat <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                        <th>Value <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                        <th>Explanation <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Thread count:</td>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.threadCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <td>The current number of live threads including both daemon and non-daemon threads.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Daemon count:</td>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.daemonThreadCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <td>The current number of live daemon threads.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Peak:</td>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.peakThreadCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <td>The peak live thread count since the Java virtual machine started or peak was reset.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Total started:</td>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.totalStarted}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <td>The total number of threads created and also started since the Java virtual machine started.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"box\">\n");
      out.write("            <div class=\"box-title\">\n");
      out.write("                <a class=\"accordion-toggle tooltip-bottom\" title=\"Close/Open\" data-toggle=\"collapse\" href=\"#collapse2\"><i class=\"fa fa-caret-down\"></i></a>\n");
      out.write("                <h3 class=\"pull-left\">\n");
      out.write("                    Threads capabilities\n");
      out.write("                </h3>\n");
      out.write("                <div class=\"box-right-nav\">\n");
      out.write("                    <a href=\"\" class=\"tooltip-bottom\" title=\"Help\"><i class=\"fa fa-info-circle\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"collapse2\" class=\"box-content accordion-body collapse in\">\n");
      out.write("                <table class=\"table table-striped tablesorter\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Stat <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                        <th>Value <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                        <th>Explanation <i class=\"fa fa-caret-down\"></i></th>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>CPU time supported:</td>\n");
      out.write("                        <td>");
      if (_jspx_meth_ano_005fwrite_005f0(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("                        <td>Does the Java virtual machine supports CPU time measurement for the current thread.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Contention monitoring supported:</td>\n");
      out.write("                        <td>");
      if (_jspx_meth_ano_005fwrite_005f1(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("                        <td>Does the Java virtual machine supports thread contention monitoring.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>Contention monitoring enabled:</td>\n");
      out.write("                        <td>");
      if (_jspx_meth_ano_005fwrite_005f2(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("                        <td>Is thread contention monitoring enabled?</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>CPU Time supported:</td>\n");
      out.write("                        <td>");
      if (_jspx_meth_ano_005fwrite_005f3(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("                        <td>Does the Java virtual machine supports CPU time measurement for the current thread.</td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>CPU Time enabled:</td>\n");
      out.write("                        <td>");
      if (_jspx_meth_ano_005fwrite_005f4(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("                        <td>Is thread CPU time measurement enabled?</td>\n");
      out.write("                    </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"text-right\">&nbsp;&nbsp;<a href=\"http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/management/ThreadMXBean.html\" class=\"btn btn-primary\">See Javadoc for details</a><br/><br/></p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../shared/jsp/Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ano_005fwrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f0 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f0_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f0.setParent(null);
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(78,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f0.setName("info");
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(78,28) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f0.setProperty("currentThreadCpuTimeSupported");
      int _jspx_eval_ano_005fwrite_005f0 = _jspx_th_ano_005fwrite_005f0.doStartTag();
      if (_jspx_th_ano_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f0);
      _jspx_th_ano_005fwrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f0, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f1 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f1_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f1.setParent(null);
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(83,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f1.setName("info");
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(83,28) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f1.setProperty("threadContentionMonitoringSupported");
      int _jspx_eval_ano_005fwrite_005f1 = _jspx_th_ano_005fwrite_005f1.doStartTag();
      if (_jspx_th_ano_005fwrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f1);
      _jspx_th_ano_005fwrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f1, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f2 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f2_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f2.setParent(null);
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(88,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f2.setName("info");
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(88,28) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f2.setProperty("threadContentionMonitoringEnabled");
      int _jspx_eval_ano_005fwrite_005f2 = _jspx_th_ano_005fwrite_005f2.doStartTag();
      if (_jspx_th_ano_005fwrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f2);
      _jspx_th_ano_005fwrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f2, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f3 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f3_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f3.setParent(null);
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(93,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f3.setName("info");
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(93,28) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f3.setProperty("threadCpuTimeSupported");
      int _jspx_eval_ano_005fwrite_005f3 = _jspx_th_ano_005fwrite_005f3.doStartTag();
      if (_jspx_th_ano_005fwrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f3);
      _jspx_th_ano_005fwrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f3, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ano_005fwrite_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ano:write
    net.anotheria.tags.WriteTag _jspx_th_ano_005fwrite_005f4 = (net.anotheria.tags.WriteTag) _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.get(net.anotheria.tags.WriteTag.class);
    boolean _jspx_th_ano_005fwrite_005f4_reused = false;
    try {
      _jspx_th_ano_005fwrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_ano_005fwrite_005f4.setParent(null);
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(98,28) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f4.setName("info");
      // /net/anotheria/moskito/webui/threads/jsp/Threads.jsp(98,28) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ano_005fwrite_005f4.setProperty("threadCpuTimeEnabled");
      int _jspx_eval_ano_005fwrite_005f4 = _jspx_th_ano_005fwrite_005f4.doStartTag();
      if (_jspx_th_ano_005fwrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fano_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_ano_005fwrite_005f4);
      _jspx_th_ano_005fwrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_ano_005fwrite_005f4, _jsp_getInstanceManager(), _jspx_th_ano_005fwrite_005f4_reused);
    }
    return false;
  }
}
